config/routes.rb
Rails.application.routes.draw do


scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
	root to: 'pages#home'
	get '/about/', to: 'pages#about'
	get '/contacts/', to: 'pages#contacts'
	resources :parents
	resources :teachers
	resources :documents
	resources :diyprojects do
		member do
			delete :delete_image_attachment
		end
	end

	get "teacher/sign_in" => "teachers_sessions#new", as: "teacher_sign_in"
	post "teacher/sign_in" => "teachers_sessions#create"
	delete "teacher/sign_out" => "teachers_sessions#destroy", via: :delete

	get "parent/sign_in" => "parents_sessions#new", as: "parent_sign_in"
	post "parent/sign_in" => "parents_sessions#create"
	delete "parent/sign_out" => "parents_sessions#destroy", via: :delete

end



end

app/views/shared/_alerts.html.erb
<div class="row">
	<div class="col-md-10 offset-md-1">
		<% flash.each do |name, msg| %>
		<div class="alert alert-<%= name %>">
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= msg %>
			</div>
		<% end %>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="errors">
				<div class="card bg-danger">
					<div class="card-header">
						<h6 class="card-title center">
							<%= pluralize(obj.errors.count, "errors") %>
							prohibited this <%= obj.class %> from being saved:
						</h6>
					</div>
					<div class="card-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">  
<hr>
  <footer>
    <ul class="list-inline text-center">
      <li class="list-inline-item">
        <a class="social-links" href="https://www.facebook.com/CREATEskills-EU-Project-1612304012192251/">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
    </ul>
     <p class="text-center">&copy; CREATEskills, 2018</p>
     <ul class="list-inline text-center">
      <li class="list-inline-item lowest-content">
        <a class="about-link" href="/about">About Us</a>
      </li>
      <li class="list-inline-item lowest-content">
        <a class="contacts-link" href="/contacts">Contacts</a>
      </li>
     </ul>

  </footer>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="#"><%= image_tag "Logo1.png", class: "homepage-logo" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to t("global.menu.home"), root_path, :class => 'nav-link' %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">DIY</a>
      </li>
      <li class="nav-item">
        <%= link_to t("global.menu.library"), documents_path, :class => 'nav-link' %>
      </li>
    
        <% if current_parent %>
        <li class="nav-item">
          <%= link_to t("global.menu.sign_out"), parent_sign_out_path, method: :delete, class: 'nav-link' %>
        </li>
        <% elsif current_teacher %>
         <li class="nav-item">
          <%= link_to t("global.menu.sign_out"), teacher_sign_out_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t ("global.menu.log_in") %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("global.menu.teacher"), teacher_sign_in_path, :class => 'dropdown-item' %>
          <%= link_to t("global.menu.parent"), parent_sign_in_path, :class => 'dropdown-item' %>
        </div>
      </li>
         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t ("global.menu.new_user") %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("global.menu.teacher"), new_teacher_path, :class => 'dropdown-item' %>
          <%= link_to t("global.menu.parent"), new_parent_path, :class => 'dropdown-item' %>
        </div>
      </li>
      <% end %>

    </ul>

    <ul class="navbar-nav navbar-right">
      <% if current_parent %>
        <li class="nav-item">
          <%= link_to t("global.menu.new-project"), new_diyproject_path, class: 'btn-custom' %>
        </li>
        <% elsif current_teacher %>
         <li class="nav-item">
          <%= link_to t("global.menu.new_document"), new_document_path, class: 'btn-custom' %>
        </li>
        <% end %>
       <li class="nav-item">
          <%= link_to_unless_current flag_icon(:lt), locale: "lt" %>
          <%= link_to_unless_current flag_icon(:gb), locale: "en" %>
          <%= link_to_unless_current flag_icon(:es), locale: "es" %>
          <%= link_to_unless_current flag_icon(:gr), locale: "gr" %>
          <%= link_to_unless_current flag_icon(:pt), locale: "pt" %>
        </li>
    </ul>
  </div>
</nav>