config/routes.rb
Rails.application.routes.draw do


scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
	root to: 'pages#home'
	get '/about/', to: 'pages#about'
	get '/contacts/', to: 'pages#contacts'
	resources :parents
	resources :teachers
	resources :documents
	resources :diyprojects do
		member do
			delete :delete_image_attachment
		end
	end

	get "teacher/sign_in" => "teachers_sessions#new", as: "teacher_sign_in"
	post "teacher/sign_in" => "teachers_sessions#create"
	delete "teacher/sign_out" => "teachers_sessions#destroy", via: :delete

	get "parent/sign_in" => "parents_sessions#new", as: "parent_sign_in"
	post "parent/sign_in" => "parents_sessions#create"
	delete "parent/sign_out" => "parents_sessions#destroy", via: :delete

end



end

app/models/diyproject.rb
class Diyproject < ApplicationRecord
	has_many_attached :images
	belongs_to :parent
	validates :title, presence: true, length: { maximum: 50}
	validates :description, presence: true, length: { maximum: 500}

end

app/controllers/diyprojects_controller.rb
class DiyprojectsController < ApplicationController
	include ParentsSessionsHelper
	before_action :set_diyproject, only: [:show, :edit, :update, :destroy]
	before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@diyprojects = Diyproject.all.order("created_at DESC")
	end

	def new
		@diyproject = Diyproject.new
	end

	def create
		@diyproject = Diyproject.new(valid_params)
		@diyproject.parent = current_parent
		if @diyproject.save
			flash[:success] = "Thank You! Your project is uploaded successfully!"
			redirect_to diyproject_path(@diyproject)
		else 
			flash[:danger] = "Something went wrong. Try again"
			render:new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @diyproject.update_attributes(valid_params)
			redirect_to diyproject_path(@diyproject)
			flash[:success] = "DIY project updated successfully"
		else
			flash[:alert] = "Error updating DIY Project. Try again"
			render :edit
		end
	end

	def destroy
		@diyproject.destroy
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js { render "destroy", locals: {id: @diyproject.id} }
		end 
	end

	def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_back(fallback_location: @diyproject_path)
  end

  private
		def valid_params
			params.require(:diyproject).permit(:title, :description, images: [])
		end

		def require_login
			if !logged_in?
				flash[:danger] = "You must be logged in to perform this action"
				redirect_back(fallback_location: root_path)
			end
		end

		def set_diyproject
			@diyproject = Diyproject.find(params[:id])
		end

	end

app/views/diyprojects/_form.html.erb
<%= render 'shared/errors', obj: @diyproject %>

<div class="col-md-6 offset-md-3">

	<div class="diyupload-form">

		<h2><%= t ".title" %></h2><br/>

<%= simple_form_for @diyproject, :html => { :multipart => true } do |f| %>
<div class="form-inputs">
<%= f.input :title, required: true, autofocus: true %>
<%= f.input :description, required: true %>
<%= f.file_field :images, multiple: true %> 
</div>

<div class="form-actions">
<%= f.button :submit, class: "btn-custom" %>
</div>
<% end %>
</div>

</div>

app/views/diyprojects/new.html.erb
<%= render 'form' %>

app/views/diyprojects/show.html.erb
<div class="container diyproject-showpage">
<div align="center">
	<div class="diy-title">
	<h1><%= @diyproject.title %></h1>
</div>
<div class="diy-description">
<%= @diyproject.description %>
</div>
</div>

<% if @diyproject.images.attached? %>
	<div class="card-columns">
		<% @diyproject.images.each do |image| %>
			<%= link_to image, 'data-lightbox': 'image' do %>
  			<%= image_tag image.variant(resize: "400x400").processed, class: "card diy-image" %>
  			<% end %>
  		<%= link_to "Delete Image", delete_image_attachment_diyproject_url(image), method: :delete, data: {confirm: "Are you sure?"} if @diyproject.parent %>
  <% end %>
  </div>
<% end %>
</div>